Repository LMS10/WINE, pull requests merged in 2025-02, with the labels that each got.

#6 [#1] Feat/공통컴포넌트 버튼
  src/components/Button.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#7 [#3] Feat/공통컴포넌트 프로필이미지
  src/app/myprofile/page.tsx
  src/components/ProfileImg.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#12 [#11] Feat/공통컴포넌트 프로필이미지
  src/components/ProfileImg.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#15 [#2] Feat/공통컴포넌트 헤더
  src/app/(with-header)/layout.tsx
  src/app/(with-header)/page.tsx
  src/app/context/auth-context.tsx
  src/app/globals.css
  src/components/Header.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#20 [#8] Feat/와인목록페이지 와인카드
  next.config.ts
  package-lock.json
  package.json
  src/app/(with-header)/wines/_components/WineCard.tsx
  src/app/(with-header)/wines/page.tsx
  src/app/globals.css
  src/components/InteractiveRating.tsx
  src/components/StaticRating.tsx
  src/types/review.ts
  src/types/wine.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#17 [#10] Feat/랜딩페이지
  public/thumbnail.png
  src/app/(with-header)/layout.tsx
  src/app/(with-header)/page.tsx
  src/assets/images/section2_lg.png
  src/components/Header.tsx
  src/components/ProfileImg.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#18 [#4] Feat/로그인_페이지_UI
  package-lock.json
  package.json
  src/app/signin/_components/LoginForm.tsx
  src/app/signin/page.tsx
Labels: Priority: Low 🐢, Type: Feature :sparkles:

#26 [#25] Feat/랜딩페이지 코드 수정
  src/app/(with-header)/layout.tsx
  src/app/(with-header)/page.tsx
  src/components/Header.tsx
Labels: Priority: Low 🐢, Type: Bug :bug:

#23 [#21] Feat/공통컴포넌트 와인카드
  src/app/myprofile/_components/KebabDropDown.tsx
  src/components/WineCard.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#28 [#25] Feat/공통컴포넌트_로그인_기능
  src/app/(with-header)/layout.tsx
  src/app/context/auth-context.tsx
  src/app/layout.tsx
  src/app/signin/_components/LoginForm.tsx
  src/app/signin/page.tsx
  src/components/Header.tsx
  src/contexts/authContext.tsx
  src/lib/auth.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#27 [#22] Feat/공통컴포넌트 모달
  src/app/layout.tsx
  src/components/modal/Modal.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#32 [#31] Feat/와인목록페이지 레이아웃
  next.config.ts
  src/app/(with-header)/layout.tsx
  src/app/(with-header)/wines/Wines.tsx
  src/app/(with-header)/wines/_components/RecommendedWine.tsx
  src/app/(with-header)/wines/_components/SearchBar.tsx
  src/app/(with-header)/wines/_components/WineCard.tsx
  src/app/(with-header)/wines/_components/WineFilter.tsx
  src/app/(with-header)/wines/_components/WineListContainer.tsx
  src/app/(with-header)/wines/page.tsx
  src/types/wine.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#34 [#33] Feat/공통컴포넌트 컨트롤바 리뷰 모달 컨트롤바
  src/app/(with-header)/wines/[id]/page.tsx
  src/assets/icons/less.svg
  src/components/ControlBar.tsx
  src/components/ReviewModalControlBar.tsx
  src/types/review-data.ts
  src/types/review-taste.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#39 [#29] Feat /회원가입 페이지 UI 및 기능 구현
  package-lock.json
  package.json
  src/app/signup/_components/SignupForm.tsx
  src/app/signup/page.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#42 [#40] Feat/공통컴포넌트 헤더 드롭다운 기능
  src/components/Header.tsx
  src/components/ProfileImg.tsx
  src/components/ProfileImgDropdown.tsx
Labels: Priority: High 🔥, Type: Feature :sparkles:

#38 [#24] Feat/내프로필페이지 내프로필
  src/app/myprofile/_components/MyProfileContainer.tsx
  src/components/ProfileImg.tsx
  tailwind.config.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#44 [#14] Feat/내프로필페이지 내가등록한와인리스트
  src/app/myprofile/_components/KebabDropDown.tsx
  src/app/myprofile/_components/MyWineListContainer.tsx
  src/components/WineCard.tsx
  src/types/wine.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#43 [#35] Feat/와인목록페이지 와인필터
  package-lock.json
  package.json
  src/app/(with-header)/wines/_components/FilterPrice.tsx
  src/app/(with-header)/wines/_components/FilterRating.tsx
  src/app/(with-header)/wines/_components/FilterTypes.tsx
  src/app/(with-header)/wines/_components/SearchBar.tsx
  src/app/(with-header)/wines/_components/WineCard.tsx
  src/app/(with-header)/wines/_components/WineFilter.tsx
  src/app/(with-header)/wines/_components/WineFilterModal.tsx
  src/app/(with-header)/wines/_components/WineListContainer.tsx
  tailwind.config.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#47 [#30] Feat/와인목록페이지 와인등록하기모달
  src/components/Dropdown.tsx
  src/components/modal/PostWineModal.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#51 [#45] Feat/내프로필페이지 내가쓴후기리스트
  src/app/myprofile/_components/MyReviewList.tsx
  src/app/myprofile/_components/myReviewMockData.json
  src/types/review-data.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#49 [#46] Feat/와인상세페이지 리뷰리스트
  src/app/(with-header)/wines/[id]/_components/ReviewContainer.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewDropdown.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewItem.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewTasteItem.tsx
  src/assets/icons/like_filled.svg
  src/types/review-data.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#54 [#53] Feat/와인목록페이지 추천와인
  package-lock.json
  package.json
  src/app/(with-header)/wines/Wines.tsx
  src/app/(with-header)/wines/_components/RecommendWineCard.tsx
  src/app/(with-header)/wines/_components/RecommendWineContainer.tsx
  src/app/(with-header)/wines/_components/RecommendedWine.tsx
  src/assets/icons/left_arrow.svg
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#57 [#48] Feat/와인상세페이지 리뷰등록하기모달
  src/components/ControlBar.tsx
  src/components/modal/PostReviewModal.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#58 [#50] Feat/와인상세페이지 별점
  public/aromas/tobacco.svg
  src/app/(with-header)/wines/[id]/_components/NoReview.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewContainer.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewItem.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewRating.tsx
  src/app/(with-header)/wines/[id]/_components/WineContainer.tsx
  src/app/(with-header)/wines/[id]/page.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#55 [#52] Feat/내프로필페이지 레이아웃
  src/app/(with-header)/myprofile/_components/KebabDropDown.tsx
  src/app/(with-header)/myprofile/_components/MyProfile.tsx
  src/app/(with-header)/myprofile/_components/MyProfileContainer.tsx
  src/app/(with-header)/myprofile/_components/MyReviewItem.tsx
  src/app/(with-header)/myprofile/_components/MyReviewListContainer.tsx
  src/app/(with-header)/myprofile/_components/MyWineListContainer.tsx
  src/app/(with-header)/myprofile/page.tsx
  src/app/myprofile/_components/MyReviewList.tsx
  src/app/myprofile/page.tsx
  src/components/ProfileImg.tsx
  src/components/WineCard.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#61 [#60] Feat/와인목록페이지 와인등록
  src/app/(with-header)/wines/_components/RecommendWineCard.tsx
  src/app/(with-header)/wines/_components/WineCard.tsx
  src/app/(with-header)/wines/_components/WineListContainer.tsx
  src/components/Dropdown.tsx
  src/components/modal/PostWineModal.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#67 [#66] Feat/공통컴포넌트 로딩스피너
  package-lock.json
  package.json
  src/app/not-found.tsx
  src/components/LoadingSpinner.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#70 [#56] Feat/내프로필페이지 내가등록한와인리스트
  src/app/(with-header)/myprofile/_components/KebabDropDown.tsx
  src/app/(with-header)/myprofile/_components/MyProfile.tsx
  src/app/(with-header)/myprofile/_components/MyProfileContainer.tsx
  src/app/(with-header)/myprofile/_components/MyReviewItem.tsx
  src/app/(with-header)/myprofile/_components/MyReviewKebabDropDown.tsx
  src/app/(with-header)/myprofile/_components/MyReviewListContainer.tsx
  src/app/(with-header)/myprofile/_components/MyWIneKebabDropDown .tsx
  src/app/(with-header)/myprofile/_components/MyWineListContainer.tsx
  src/app/(with-header)/myprofile/page.tsx
  src/components/Dropdown.tsx
  src/components/WineCard.tsx
  src/components/modal/DeleteWineModal.tsx
  src/components/modal/Modal.tsx
  src/components/modal/PatchWineForm.tsx
  src/contexts/authContext.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#63 [#41] Feat/카카오로그인 기능
  src/app/(with-header)/layout.tsx
  src/app/(with-header)/myprofile/_components/MyProfile.tsx
  src/app/(with-header)/wines/_components/RecommendWineCard.tsx
  src/app/(with-header)/wines/_components/WineCard.tsx
  src/app/(with-header)/wines/_components/WineListContainer.tsx
  src/app/layout.tsx
  src/app/oauth/google/page.tsx
  src/app/oauth/kakao/_components/KakaoCallback.tsx
  src/app/oauth/kakao/page.tsx
  src/app/signin/_components/LoginForm.tsx
  src/app/signin/api/KakaoApi.tsx
  src/app/signin/page.tsx
  src/app/signup/_components/SignupForm.tsx
  src/components/Header.tsx
  src/contexts/AuthProvider.tsx
  src/lib/auth.tsx
Labels: Priority: High 🔥, Type: Feature :sparkles:

#69 [#65] Feat/와인상세페이지 수정/삭제
  src/app/(with-header)/wines/[id]/_components/NoReview.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewContainer.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewDropdown.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewItem.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewRating.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewTasteItem.tsx
  src/app/(with-header)/wines/[id]/_components/WineContainer.tsx
  src/components/InteractiveRating.tsx
  src/components/modal/Modal.tsx
  src/components/modal/PatchReviewForm.tsx
  src/components/modal/PostReviewModal.tsx
  src/lib/fetchWineDetail.ts
  src/types/review-data.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#72 [#71] Feat/내프로필페이지 내가쓴후기리스트
  src/app/(with-header)/myprofile/_components/MyProfile.tsx
  src/app/(with-header)/myprofile/_components/MyProfileContainer.tsx
  src/app/(with-header)/myprofile/_components/MyReviewItem.tsx
  src/app/(with-header)/myprofile/_components/MyReviewKebabDropDown.tsx
  src/app/(with-header)/myprofile/_components/MyReviewListContainer.tsx
  src/app/(with-header)/myprofile/_components/MyWineListContainer.tsx
  src/app/(with-header)/myprofile/page.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#78 [#74] Feat/공통컴포넌트 새로고침
  src/app/(with-header)/myprofile/_components/MyProfileContainer.tsx
  src/app/(with-header)/myprofile/_components/MyReviewListContainer.tsx
  src/app/(with-header)/myprofile/_components/MyWineListContainer.tsx
  src/components/Refresh.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#76 [#75] Refactor/와인목록페이지 추천와인
  src/app/(with-header)/wines/_components/RecommendWine.tsx
  src/app/(with-header)/wines/_components/RecommendWineContainer.tsx
  src/app/(with-header)/wines/_components/skeleton/RecommendWineCardSkeleton.tsx
  src/app/(with-header)/wines/_components/skeleton/RecommendWineListSkeleton.tsx
  src/lib/fetchRecommendWine.ts
Labels: Priority: Medium :bookmark:, Type: Improve UX :arrow_up:, Type: Refactor :recycle:

#82 [#73] Feat/와인목록페이지 무한스크롤
  src/app/(with-header)/myprofile/_components/MyWineListContainer.tsx
  src/app/(with-header)/wines/Wines.tsx
  src/app/(with-header)/wines/_components/WineCard.tsx
  src/app/(with-header)/wines/_components/WineFilterModal.tsx
  src/app/(with-header)/wines/_components/WineListContainer.tsx
  src/app/globals.css
  src/lib/fetchWines.ts
  src/types/wine.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#81 [#79] Feat/구글로그인 기능 구현
  next.config.ts
  src/app/oauth/google/_components/GoogleCallback.tsx
  src/app/oauth/google/page.tsx
  src/app/signin/_components/LoginForm.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#84 [#83] Feat/공통컴포넌트 토스트
  package-lock.json
  package.json
  src/app/layout.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#87 [#77] Refactor/와인상세페이지 와인 카드
  src/app/(with-header)/wines/[id]/_components/NoReview.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewContainer.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewDropdown.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewItem.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewRating.tsx
  src/app/(with-header)/wines/[id]/_components/WineContainer.tsx
  src/app/(with-header)/wines/[id]/_components/skeleton/WineContainerSkeleton.tsx
  src/app/(with-header)/wines/[id]/page.tsx
  src/components/modal/PostReviewModal.tsx
  src/lib/fetchWineDetail.ts
  src/types/review-data.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#86 [#85] Feat/로그인 로딩페이지 UI
  src/app/oauth/google/_components/GoogleCallback.tsx
  src/app/oauth/kakao/_components/KakaoCallback.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#91 [#89] Refactor/회원가입 에러메세지
  package-lock.json
  src/app/signin/api/KakaoApi.tsx
  src/app/signup/_components/SignupForm.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Refactor :recycle:

#92 [#88] Refactor/와인상세페이지 리뷰
  src/app/(with-header)/wines/[id]/_components/NoReview.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewAroma.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewContainer.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewDropdown.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewItem.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewRating.tsx
  src/app/(with-header)/wines/[id]/_components/ReviewTasteItem.tsx
  src/app/(with-header)/wines/[id]/_components/skeleton/ReviewContainerSkeleton.tsx
  src/app/(with-header)/wines/[id]/_components/skeleton/WineContainerSkeleton.tsx
  src/app/(with-header)/wines/[id]/_components/skeleton/WineDetailSkeleton.tsx
  src/app/(with-header)/wines/[id]/page.tsx
  src/components/ControlBar.tsx
  src/components/InteractiveRating.tsx
  src/components/modal/PatchReviewForm.tsx
  src/components/modal/PostReviewModal.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#94 [#90] Refactor/와인목록페이지 와인목록
  src/app/(with-header)/page.tsx
  src/app/(with-header)/wines/_components/FilterPrice.tsx
  src/app/(with-header)/wines/_components/FilterRating.tsx
  src/app/(with-header)/wines/_components/FilterTypes.tsx
  src/app/(with-header)/wines/_components/RecommendWineContainer.tsx
  src/app/(with-header)/wines/_components/WineFilter.tsx
  src/app/(with-header)/wines/_components/WineFilterModal.tsx
  src/app/(with-header)/wines/_components/WineListContainer.tsx
  src/app/(with-header)/wines/_components/skeleton/RecommendWineCardSkeleton.tsx
  src/app/(with-header)/wines/_components/skeleton/WineCardSkeleton.tsx
  src/app/(with-header)/wines/_components/skeleton/WineListSkeleton.tsx
  src/app/layout.tsx
  src/app/signin/_components/LoginForm.tsx
  src/app/signup/page.tsx
  src/components/Refresh.tsx
  src/components/modal/PostWineModal.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#96 [#80] Feat/내프로필페이지 무한스크롤
  src/app/(with-header)/myprofile/_components/MyProfile.tsx
  src/app/(with-header)/myprofile/_components/MyProfileContainer.tsx
  src/app/(with-header)/myprofile/_components/MyReviewItem.tsx
  src/app/(with-header)/myprofile/_components/MyReviewKebabDropDown.tsx
  src/app/(with-header)/myprofile/_components/MyReviewListContainer.tsx
  src/app/(with-header)/myprofile/_components/MyWIneKebabDropDown .tsx
  src/app/(with-header)/myprofile/_components/MyWineListContainer.tsx
  src/app/(with-header)/myprofile/_components/skeleton/MyProfileSkeleton.tsx
  src/app/(with-header)/myprofile/_components/skeleton/MyReviewItemSkeleton.tsx
  src/app/(with-header)/myprofile/_components/skeleton/MyWineItemSkeleton.tsx
  src/app/(with-header)/myprofile/page.tsx
  src/components/WineCard.tsx
  src/components/modal/PatchReviewForm.tsx
  src/components/modal/PatchWineForm.tsx
  src/lib/fetchImage.ts
  src/lib/fetchMyReivew.ts
  src/lib/fetchMyWine.ts
  src/lib/fetchUser.ts
  src/lib/fetchWines.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#97 [#93] Refactor/공통 커스텀스크롤바
  src/app/(with-header)/myprofile/_components/MyReviewKebabDropDown.tsx
  src/app/(with-header)/myprofile/_components/MyWIneKebabDropDown .tsx
  src/app/(with-header)/wines/[id]/_components/ReviewDropdown.tsx
  src/app/(with-header)/wines/_components/WineFilterModal.tsx
  src/app/globals.css
  src/components/Header.tsx
  src/components/modal/DeleteModal.tsx
  src/components/modal/Modal.tsx
  src/components/modal/PatchReviewModal.tsx
  src/components/modal/PatchWineModal.tsx
  src/components/modal/PostReviewModal.tsx
  src/components/modal/PostWineModal.tsx
  src/hooks/useScrollLock.ts
Labels: Priority: Medium :bookmark:, Type: Improve UX :arrow_up:

#100 [#99] Refactor/와인목록페이지
  src/app/(with-header)/myprofile/_components/MyWIneKebabDropDown .tsx
  src/app/(with-header)/myprofile/_components/MyWineListContainer.tsx
  src/app/(with-header)/wines/_components/WineCard.tsx
  src/app/(with-header)/wines/_components/WineListContainer.tsx
  src/components/Button.tsx
  src/components/modal/PatchWineModal.tsx
  src/components/modal/PostReviewModal.tsx
  src/components/modal/PostWineModal.tsx
  src/types/wine.ts
  tailwind.config.ts
Labels: Priority: Medium :bookmark:, Type: Bug :bug:, Type: Improve UX :arrow_up:, Type: Refactor :recycle:

#101 [#98] Refactor/공통컴포넌트 모달
  src/app/(with-header)/myprofile/_components/MyReviewKebabDropDown.tsx
  src/app/(with-header)/myprofile/_components/MyWIneKebabDropDown .tsx
  src/app/(with-header)/wines/[id]/_components/ReviewDropdown.tsx
  src/app/signin/api/KakaoApi.tsx
  src/components/ControlBar.tsx
  src/components/Dropdown.tsx
  src/components/InteractiveRating.tsx
  src/components/ReviewModalControlBar.tsx
  src/components/modal/Modal.tsx
  src/components/modal/ModalFormInput.tsx
  src/components/modal/PatchReviewModal.tsx
  src/components/modal/PatchWineModal.tsx
  src/components/modal/PostReviewModal.tsx
  src/components/modal/PostWineModal.tsx
Labels: Priority: Low 🐢, Type: Bug :bug:, Type: Refactor :recycle:
